In [2]:
import numpy as np

Let's pretend we're looking at the output of the neural network or the activation of last layer.
We have 5 different numbers that represent 5 different nodes at the output layer

In [3]:
a = np.random.rand(5)
a

array([0.76956597, 0.27018298, 0.79723267, 0.0882895 , 0.64055635])

First step is to exponentiate them so they're all positive

In [4]:
exp_a = np.exp(a)
exp_a

Now sum of answer should be equal to 1

In [5]:
answer = exp_a / exp_a.sum()
answer.sum()

Lately we're going to work with multiple samples at the same time.
This mean we won't have 1-D array of length 5 but 2-D array of size (N,5)

In [6]:
A = np.random.rand(100, 5)
A

array([[3.14079812e-01, 1.40946730e-01, 3.60890383e-01, 4.91490902e-01,
        4.27483533e-01],
       [2.53448471e-01, 6.73574707e-01, 1.53769317e-01, 5.29320732e-02,
        4.73967303e-01],
       [1.60034927e-01, 3.51654495e-01, 6.74731360e-01, 6.73422557e-01,
        8.96568360e-01],
       [9.12568846e-03, 4.75467657e-01, 3.70018804e-01, 6.93663219e-01,
        7.80546830e-01],
       [5.64081443e-01, 7.03989605e-01, 9.35654942e-02, 4.99641490e-01,
        5.76216196e-01],
       [8.22756252e-01, 5.07736131e-01, 7.89184213e-01, 5.75261472e-01,
        4.58674761e-01],
       [9.00006807e-01, 5.02227561e-01, 9.72603918e-01, 3.25053693e-02,
        5.43231305e-01],
       [1.72404628e-01, 7.00591926e-01, 3.45379576e-01, 9.41169960e-01,
        5.03747407e-01],
       [9.17688966e-01, 9.24700706e-01, 8.30215813e-01, 3.30305719e-02,
        9.80674796e-01],
       [7.90541254e-01, 9.10932865e-01, 6.16536022e-01, 9.82265176e-01,
        9.87237399e-02],
       [4.58542528e-01, 2.3337

In [7]:
exp_A = np.exp(A)
exp_A

axis = 1 because we want to sum by rows
keepdims = True otherwise errors will be thrown (dimensions won't match)

In [8]:
answer_A = exp_A / exp_A.sum(axis=1, keepdims=True)
answer_A[:5]

array([[0.19219108, 0.16163763, 0.20140155, 0.22949958, 0.21527016],
       [0.18207265, 0.27714256, 0.16479902, 0.14899152, 0.22699424],
       [0.13082216, 0.15845307, 0.21888255, 0.21859627, 0.27324595],
       [0.12233232, 0.19501632, 0.17549919, 0.24256721, 0.26458496],
       [0.21165593, 0.24343991, 0.1322172 , 0.19844699, 0.21423997]])

In [9]:
answer_A.sum(axis=1)

Check what denominator gives you

In [10]:
denominator = answer_A.sum(axis=1, keepdims=True)
print(denominator.shape)
denominator

(100, 1)


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],