In [12]:
import numpy as np

Let's pretend we're looking at the output of the neural network or the activation of last layer.
We have 5 different numbers that represent 5 different nodes at the output layer

In [13]:
a = np.random.rand(5)
a

array([0.15392532, 0.91507277, 0.64078832, 0.5024887 , 0.7347537 ])

First step is to exponentiate them so they're all positive

In [14]:
exp_a = np.exp(a)
exp_a

array([1.16640378, 2.49695695, 1.8979765 , 1.65282956, 2.08496841])

Now sum of answer should be equal to 1

In [15]:
answer = exp_a / exp_a.sum()
answer.sum()

1.0

Lately we're going to work with multiple samples at the same time.
This mean we won't have 1-D array of length 5 but 2-D array of size (N,5)

In [16]:
A = np.random.rand(100, 5)
A[:5]

array([[0.12086773, 0.70742444, 0.96899696, 0.02338244, 0.0560488 ],
       [0.32379984, 0.99908242, 0.7947827 , 0.69337649, 0.29109479],
       [0.28431641, 0.65884824, 0.61278831, 0.26222079, 0.26901642],
       [0.57393002, 0.43170681, 0.1393481 , 0.16911432, 0.32904821],
       [0.50446287, 0.25693321, 0.26311756, 0.34353821, 0.93918489]])

In [17]:
exp_A = np.exp(A)
exp_A[:5]

array([[1.12847564, 2.02875933, 2.63529983, 1.02365795, 1.0576493 ],
       [1.38237058, 2.71578874, 2.21395986, 2.00045867, 1.33789139],
       [1.32885333, 1.9325652 , 1.84557024, 1.2998135 , 1.30867663],
       [1.77523004, 1.53988358, 1.14952418, 1.18425551, 1.38964486],
       [1.65609575, 1.29295877, 1.30097965, 1.4099274 , 2.55789561]])

axis = 1 because we want to sum by rows
keepdims = True otherwise errors will be thrown (dimensions won't match)

In [18]:
answer_A = exp_A / exp_A.sum(axis=1, keepdims=True)
answer_A[:5]

array([[0.14331957, 0.25765812, 0.33469046, 0.13000743, 0.13432442],
       [0.14324387, 0.2814152 , 0.22941474, 0.20729134, 0.13863485],
       [0.17223213, 0.25047897, 0.23920359, 0.16846828, 0.16961703],
       [0.25221573, 0.21877889, 0.1633186 , 0.16825305, 0.19743373],
       [0.20152404, 0.15733527, 0.1583113 , 0.17156874, 0.31126066]])

In [19]:
answer_A.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Check what denominator gives you

In [21]:
denominator = answer_A.sum(axis=1, keepdims=True)
print(denominator.shape)
denominator[:5]

(100, 1)


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])